Repository atapas/vento-client, pull requests merged in 2020-04, with the labels that each got.

#12 Improving Readme
  README.md
  client/README.md
  client/readme_images/assetlist.png
  client/readme_images/createEdit.png
  client/readme_images/editDelete.png
  client/readme_images/loginLogout.png
  client/readme_images/ventoFlow.png
  database/README.md
  database/erd/db_erd_diag.png
  rest-services/README.md
Labels: enhancement

#24 Bugfix/#17 client readme
  client/README.md
  client/readme_images/assetlist.png
  client/readme_images/createEdit.png
  client/readme_images/editDelete.png
  client/readme_images/loginLogout.png
Labels: documentation, merge-ready

#31 Fixed:#27_deleting multiple reords in asset-notification-map
  rest-services/api/controllers/AssetNotificationMapController.js
Labels: merge-ready

#33 Fixed:bug #28 multidelete in asset-consumer-map
  rest-services/api/controllers/AssetConsumerMapController.js
Labels: merge-ready

#29 Feature/26 add multicreate for apis
  rest-services/api/controllers/AssetConsumerMapController.js
  rest-services/api/controllers/AssetController.js
  rest-services/api/controllers/AssetNotificationMapController.js
  rest-services/api/controllers/DepartmentController.js
  rest-services/api/controllers/NotificationController.js
  rest-services/api/controllers/PermissionController.js
  rest-services/api/controllers/ProductController.js
  rest-services/api/controllers/RoleController.js
  rest-services/api/controllers/RolePermissionMapController.js
  rest-services/api/controllers/UserController.js
  rest-services/config/routes.js
Labels: merge-ready

#36 fixed; #35_Warning in Sails log for updatedAt
  rest-services/api/controllers/AssetConsumerMapController.js
  rest-services/api/controllers/AssetNotificationMapController.js
  rest-services/api/models/Asset.js
  rest-services/api/models/AssetNotificationMap.js
  rest-services/api/models/RolePermissionMap.js
  rest-services/api/models/User.js
  rest-services/config/models.js
Labels: merge-ready
